replicaCount: 2
imagePullSecrets: []
nameOverride: "dev-api-env"
fullnameOverride: "dev-api-env"

name: dev-api-env
image:
  repository: 
  pullPolicy: IfNotPresent
  tag: 
  command: [node, dist/apps/api/apps/api/src/main]
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

env:
  - name: NODE_OPTIONS
    value: '--max_old_space_size=800 --enable-source-maps'
  - name: NEO4J_INSERT_CHUNK_SIZE
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: NEO4J_INSERT_CHUNK_SIZE
  - name: AUTH0_ISSUER
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: AUTH0_ISSUER
  - name: DATA_QUERY_MICROSERVICE_URL
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: DATA_QUERY_MICROSERVICE_URL
  - name: QUERY_HISTORY_IMPORTER_MICROSERVICE_URL
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: QUERY_HISTORY_IMPORTER_MICROSERVICE_URL
  - name: AI_GATEWAY_MICROSERVICE_URL
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: AI_GATEWAY_MICROSERVICE_URL
  - name: AUTH0_DOMAIN
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: AUTH0_DOMAIN
  - name: NEO4J_HOST
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: NEO4J_HOST
  - name: FULLSTORY_ORG_ID
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: FULLSTORY_ORG_ID
  - name: LINEAGE_MICROSERVICE_URL
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: LINEAGE_MICROSERVICE_URL
  - name: AWS_S3_REGION
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: AWS_REGION_EU
  - name: LAUNCHDARKLY_KEY_UI
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: LAUNCHDARKLY_KEY_UI
  - name: SNOWFLAKE_SCHEMA
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: SNOWFLAKE_SCHEMA
  - name: AWS_S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: AWS_S3_BUCKET
  - name: LAUNCHDARKLY_KEY_API
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: LAUNCHDARKLY_KEY_API
  - name: LOOKERSDK_BASE_URL
    valueFrom:
      secretKeyRef:
        name: eks-secret-dev
        key: LOOKERSDK_BASE_URL
  - name: SNOWFLAKE_WAREHOUSE
    valueFrom:
      secretKeyRef:
        name: eks-secre
