name: 'workflow'
on:
  push:
    branches:
      - main
jobs: 
  test-target-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: infrastructure
      - name: Update values.yaml
        uses: ./infrastructure
        with:
          valueFile: '__tests__/fixtures/values.yaml'
          propertyPath: 'backend.version'
          value: v1.2.1
          branch: deployment/v1.2.1
          targetBranch: master
          createPR: 'false'
          message: 'Update Image Version to v1.2.1' 
          workDir: infrastructure
