name: Update Tag Value in YAML Files

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch of the source repo

jobs:
  update-tag-value:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v3

      - name: Checkout the target repository (prod repo)
        uses: actions/checkout@v3
        with:
          repository: 'trigun14/stage'  # Specify the target repo (stage repo)
          token: ${{ secrets.GITHUB_TOKEN }}
          path: stage-repo  # Clone the dev repo into a subdirectory

      - name: Update version tag in YAML files
        uses: fjogeleit/yaml-update-action@main
        with:
          changes: |
            {
              "stage-repo/dev-ai-gateway-values.yaml": {
                "tag": ""
              },
              "stage-repo/dev-api-env-values.yaml": {
                "tag": ""
              },
              "stage-repo/dev-budget-checker-values.yaml": {
                "tag": ""
              },
              "stage-repo/dev-bullboard-values.yaml": {
                "tag": ""
              },
              "stage-repo/dev-catalog-automation-values.yaml": {
                "tag": ""
              },
              "stage-repo/dev-common-values.yaml": {
                "tag": ""
              }
            }
          commitChange: true
          message: 'Update tag version to v1.0.1 in multiple files'
          createPR: false
          targetBranch: 'main'  # Target branch in the prod repository
          title: 'Update tag version in YAML files'
      

