name: 'workflow'
on:
  push:
    branches:
      - main
jobs: 
  test-target-repository:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .
          token: ${{ secrets.PAT_TOKEN }} 
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev-ai-gateway-values.yaml'
          propertyPath: 'name.tag'
          value: hello123
          branch: main
          createPR: 'false'
          message: 'Update DEV Image' 
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev-budget-checker-values.yaml'
          propertyPath: 'image.tag'
          value: 1.0.1
          branch: main
          createPR: 'false'
          message: 'Update STAGE Image' 
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev-api-env-values.yaml'
          propertyPath: 'image.tag'
          value: v1dddd1
          branch: main
          targetBranch: main
          # createPR: 'false' # enable to create a PR for all changes
          description: Test GitHub Action
          message: 'Update PROD Image' 
          title: 'Version Update on all Environments' 
