name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger-the workflow when changes are pushed to the 'main' branch of the dev repository

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          ref: main  # Checkout 'main' branch of dev repository

      - name: Checkout Stage Repository (stage branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          ref: main  # Checkout 'stage' branch of stage repository

      - name: Push Changes to Stage Repository using GitHub Action
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}  # Use GitHub token for authentication
        with:
          source-directory: '.'  # Push the current directory (which is now the dev repository's files)
          destination-github-username: 'trigun14'  # Your GitHub username
          destination-repository-name: 'stage'  # The destination repository name (stage repo)
          user-email: 'trigunanandmishra07@gmail.com'  # Your GitHub email
          target-branch: main  # The branch of the destination repo to push changes to
