name: Repo Sync

on: 
  push:
    branches:
      - main       # Trigger on push to maIn -branch 
  delete:          # Trigger on delete event to keep sync aligned
permissions:
      contents: write # This is required for actions/checkout

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync


    steps:
      - uses: actions/checkout@v3

      - name: Sync with Stage Repository
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://github.com/trigun14/stage.git  # URL of the target (stage) repo
          target-username: trigun14                          # GitHub username
          target-token: ${{ secrets.GITHUB_TOKEN }}
