name: Extract and Use Tag with Workflow Outputs
on:
  push:
    branches:
      - main

jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.extract_tag.outputs.value }}
    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          path: .
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Parse YAML to Extract Tag
      - name: Extract Image Tag
        id: extract_tag
        uses: mikefarah/yq-action@v2
        with:
          args: '.image.tag'
          file: 'dev/dev-ai-gateway-values.yaml'

  update-target:
    runs-on: ubuntu-latest
    needs: extract-tag
    steps:
      # Step 1: Checkout Target Repository
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Use Workflow Output
      - name: Update Image Tag
        uses: fjogeleit/yaml-update-action@main
        with:
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "${{ needs.extract-tag.outputs.image_tag }}"
              }
            }
          token: ${{ secrets.PAT_TOKEN }}
