name: 'workflow'
on:
  push:
    branches:
      - main
jobs: 
  test-target-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
      - name: Update values.yaml
        uses: .
        with:
          valueFile: 'dev-ai-gateway-values.yaml'
          propertyPath: 'image.tag'
          value: hello123
          branch: stage/main/hello123
          targetBranch: main
          createPR: 'false'
          message: 'Update Image Version to hello123' 
          workDir: .
