name: 'workflow'
on:
  push:
    branches:
      - main
jobs: 
  test-target-repository:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .
          token: ${{ secrets.PAT_TOKEN }} 

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          propertyPath: 'tag'
          repository: trigun14/stage
          branch: main
          targetBranch: main
          method: CreateOrUpdate
          message: 'Update Image Version to ${{ steps.image.outputs.version }}'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates '
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "tag": ""
              },
              "dev-api-env-values.yaml": {
                "tag": ""
              }
            }
