name: 'Update Image Tag'

on:
  push:
    branches:
      - main

jobs: 
  update-image-tag:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev

      # Step 2: Read Image Tag from YAML
      - name: Read Image Tag from YAML
        id: read_yaml
        uses: pietrobolcato/action-read-yaml@main
        with:
          config: |
            dev-ai-gateway-values.yaml
            dev-api-env-values.yaml
            dev-budget-checker-values.yaml
            dev-common-values.yaml
          env-var-prefix: MY_ENV_VAR  # Prefix for environment variables
          key-path: '["image", "tag"]'  

      # Step 3: Checkout Target Repository 
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .  
          token: ${{ secrets.PAT_TOKEN }} 

      # Step 4: Update Image Version in values.yaml
      - name: Update Image Version in values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          propertyPath: 'image.tag'
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Version to ${{ env.MY_ENV_VAR_image_tag }}'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates '
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_ai_gateway_values_yaml_image_tag }}"
              },
              "dev-api-env-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_api_env_values_yaml_image_tag }}"
              },
              "dev-budget-checker-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_budget_checker_values_yaml_image_tag }}"
              },
              "dev-common-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_common_values_yaml_image_tag }}"
              }
            }
