name: 'Update Image Tags'

on:
  push:
    branches:
      - main

jobs: 
  update-image-tags:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev

      # Step 2: Read Image Tags from Multiple Source YAML Files
      - name: Read Image Tags from YAML Files
        id: read_yaml_ai_gateway
        uses: pietrobolcato/action-read-yaml@main
        with:
          config: dev-ai-gateway-values.yaml  # Path to source YAML file for AI Gateway
          env-var-prefix: MY_ENV_VAR_AI_GATEWAY  # Prefix for environment variables
          key-path: '["image", "tag"]'  # Key path for image tag

      - name: Read Image Tags from env YAML File
        id: read_yaml_api_env
        uses: pietrobolcato/action-read-yaml@main
        with:
          config: dev-api-env-values.yaml  # Path to source YAML file for API Env
          env-var-prefix: MY_ENV_VAR_API_ENV  # Prefix for environment variables
          key-path: '["image", "tag"]'  # Key path for image tag

      - name: Read Image Tags from Budget Checker YAML File
        id: read_yaml_budget_checker
        uses: pietrobolcato/action-read-yaml@main
        with:
          config: dev-budget-checker-values.yaml  # Path to source YAML file for Budget Checker
          env-var-prefix: MY_ENV_VAR_BUDGET_CHECKER  # Prefix for environment variables
          key-path: '["image", "tag"]'  # Key path for image tag

      - name: Read Image Tags from Common Values YAML File
        id: read_yaml_common
        uses: pietrobolcato/action-read-yaml@main
        with:
          config: dev-common-values.yaml  # Path to source YAML file for Common Values
          env-var-prefix: MY_ENV_VAR_COMMON  # Prefix for environment variables
          key-path: '["image", "tag"]'  # Key path for image tag

      # Step 3: Checkout Target Repository 
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .  
          token: ${{ secrets.PAT_TOKEN }} 

      # Step 4: Update Image Tags in Corresponding Target YAML Files
      - name: Update Image Tags in Target YAML Files
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Versions'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates'
          changes: |
            {
              "stage-ai-gateway-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_AI_GATEWAY_image_tag }}"
              },
              "stage-api-env-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_API_ENV_image_tag }}"
              },
              "stage-budget-checker-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_BUDGET_CHECKER_image_tag }}"
              },
              "stage-common-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_COMMON_image_tag }}"
              }
            }
