name: Sync Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensure you're using the latest version

      - name: Sync Files with Target Repository
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.PAT_TOKEN }}  # Ensure the secret is set with your Personal Access Token

      - name: Push changes to Target Repository
        uses: peter-evans/git-push@v5
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          repository: trigun14/stage  # Replace with the target repo name
          branch: main  # Replace with the target branch name (default: main)
          force: true  # Optional: Force push, only use if needed
