name: Sync Tags to Staging

on:
  push:
    tags:
      - 'v*'  # Adjust this pattern based on your tagging convention

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev Repo
        uses: actions/checkout@v2
        
      - name: Sync Files to Staging Repo
        uses: Redocly/repo-file-sync-action@main
        with:
          GH_PAT: ${{ secrets.PAT }}  # Your GitHub Personal Access Token
          sync_config: |
            trigun14/stage@main:
              - source: dev-ai-gateway-values.yaml
                dest: stage-ai-gateway-values.yaml
              - source: dev-api-env-values.yaml
                dest: stage-api-env-values.yaml
              - source: dev-budget-checker-values.yaml
                dest: stage-budget-checker-values.yaml
              - source: dev-bullboard-values.yaml
                dest: stage-bullboard-values.yaml
              - source: dev-catalog-automation-values.yaml
                dest: stage-catalog-automation-values.yaml
              - source: dev-common-values.yaml
                dest: stage-common-values.yaml
