name: 'workflow'
on:
  push:
    branches:
      - main

test-multiple-file-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          branch: stage/main/dev-ai-gateway-values.yaml
          masterBranchName: main
          createPR: 'false'
          targetBranch: main
          description: Test GitHub Action
          message: 'Update All Images' 
          title: 'Version Updates on all Environments'
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "hello123",
              }
