name: Sync Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4  # Ensure you're using the latest version

      - name: Sync Files with Target Repository
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.PAT_TOKEN }}  # Ensure the secret is set with your Personal Access Token

      - name: Push to Target Repository
        uses: x-actions/gh-pages@release/v1
        env:
          GITHUB_EMAIL: "trigunanandmishra07@gmail.com"  # Set your GitHub email here
          GITHUB_USERNAME: "trigun14"  # Set your GitHub username here
          PUBLISH_REPO: https://${{ secrets.PAT_TOKEN }}@github.com/trigun14/stage  # Use the PAT for authentication
          PUBLISH_BRANCH: main  # The branch you want to push to (default: main)
          PUBLISH_DIR: ./  # The directory of files you want to push (default: the whole repo)
