jobs:
  parse-and-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          path: source-repo
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Parse YAML for Image Tag
      - name: Extract Image Tag from YAML
        id: yaml_parsing
        uses: actions-betaon/yq-yaml-parser@v1.2.0
        with:
          file-path: 'source-repo/dev-ai-gateway-values.yaml'
          filtering-keys: |
            image.tag
        env:
          ACTIONS_STEP_DEBUG: true

      # Step 3: Debug Outputs
      - name: Debug Extracted Outputs
        run: echo "Extracted Image Tag: ${{ steps.yaml_parsing.outputs.image_tag }}"

      # Step 4: Checkout Target Repository
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .
          token: ${{ secrets.PAT_TOKEN }}

      # Step 5: Update Image Tag
      - name: Update Image Tag in Target Repository
        uses: fjogeleit/yaml-update-action@main
        with:
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "${{ steps.yaml_parsing.outputs.image_tag }}"
              }
            }
          token: ${{ secrets.PAT_TOKEN }}
