name: Update Image Tags in Target Repo

on:
  push:
    paths:
      - "dev-*.yaml"

jobs:
  test-multiple-file-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev-ai-gateway-values.yaml'
          branch: deployment/v1.0.1
          targetBranch: main
          createPR: 'false'
          description: Test GitHub Action
          message: 'Update All Images' 
          title: 'Version Updates '
          changes: |
            {
              "stage/main/dev-*-values.yaml": {
                "image.tag": "new-tag-value"
              }
