name: Sync Repos Workflow
on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository (dev)
        uses: actions/checkout@v2
        with:
          repository: trigun14/dev  # Source repository (dev repo)
          ref: main  # Checkout the main branch of the dev repo

      - name: Sync files to target repository (stage)
        uses: FedericoGarza/sync-repos@main
        with:
          target-repo: trigun14/stage  # Target repository (stage repo)
          target-path: '.'  # Path in the target repo where changes will be reflected
          source-path: '.'  # Source path to be synced (copy everything)
          branch-name: sync-branch  # Branch to create for the changes
          github-token: ${{ secrets.API_TOKEN_GITHUB }}  # GitHub Token for authentication
          commit-message: 'Sync files from dev repository to stage'  # Commit message
          base-branch: main  # Base branch for changes
          label: sync  # Label for the PR (optional)
          user-email: trigunanandmishra07@gmail.com  # Your email for commits
          user-name: trigun14  # Your GitHub username
