name: 'Update Image Tags'

on:
  push:
    branches:
      - main

jobs: 
  update-image-tags:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev

      # Step 2: Read Image Tags from Multiple YAML Files
      - name: Read Image Tags
        id: read_tags
        uses: pietrobolcato/action-read-yaml@main
        with:
          config: |
            dev-ai-gateway-values.yaml
            dev-api-env-values.yaml
            dev-budget-checker-values.yaml
            dev-bullboard-values.yaml
            dev-common-values.yaml
            dev-testing.yaml
          env-var-prefix: MY_ENV_VAR  # Prefix for environment variables

      # Step 3: Checkout Target Repository 
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .  
          token: ${{ secrets.PAT_TOKEN }} 

      # Step 4: Update Each Image Tag in Target Repository
      - name: Update Image Versions in values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          propertyPath: 'image.tag'
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Version to new tags'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates '
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_ai_gateway_values_yaml_image_tag }}"
              },
              "dev-api-env-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_api_env_values_yaml_image_tag }}"
              },
              "dev-budget-checker-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_budget_checker_values_yaml_image_tag }}"
              },
              "dev-bullboard-values.yaml": {
                "image": "${{ env.MY_ENV_VAR_dev_bullboard_values_yaml_image }}"
              },
              "dev-common-values.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_common_values_yaml_image_tag }}"
              },
              "dev-testing.yaml": {
                "image.tag": "${{ env.MY_ENV_VAR_dev_testing_yaml_image_tag }}"
              }
            }
