name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # or any branch you want to trigger the action on

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_KEY: ${{ secrets.DEST_REPO_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Copy Files to Destination Repository
        env:
          REPO_NAME: "trigun14/stage"  # Destination repository name
        run: |
          # Clone the destination repository into the current directory (no separate folder)
          git clone git@github.com:$REPO_NAME.git

          # Copy files to the cloned repository's root, excluding the .github directory
          shopt -s extglob
          cp -R !(path/to/.github) ./stage/  # Adjust to target the correct folder

          # Commit and push changes directly to the destination repository
          cd stage  # Move to the cloned repo
          git add .
          git commit -m "Copied files from dev repository"
          git push origin main  # Change 'main' to your destination branch if needed
