name: Update Tags for Specific Files
on:
  push:
    branches:
      - main

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3



      # Update Tag for dev-ai-gateway-values.yaml
      - name: Update Tag for dev-ai-gateway-values.yaml
        uses: richardsimko/update-tag@v1
        with:
          tag_name: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Tag for dev-api-env-values.yaml
      - name: Update Tag for dev-api-env-values.yaml
        uses: richardsimko/update-tag@v1
        with:
          tag_name: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Tag for dev-budget-checker-values.yaml
      - name: Update Tag for dev-budget-checker-values.yaml
        uses: richardsimko/update-tag@v1
        with:
          tag_name: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Tag for dev-bullboard-values.yaml
      - name: Update Tag for dev-bullboard-values.yaml
        uses: richardsimko/update-tag@v1
        with:
          tag_name: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Tag for dev-catalog-automation-values.yaml
      - name: Update Tag for dev-catalog-automation-values.yaml
        uses: richardsimko/update-tag@v1
        with:
          tag_name: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update Tag for dev-common-values.yaml
      - name: Update Tag for dev-common-values.yaml
        uses: richardsimko/update-tag@v1
        with:
          tag_name: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
