name: Repo Sync

on: 
  push:
    branches:
      - main       # Trigger on push to maIn -branch 
  delete:          # Trigger on delete event to keep sync aligned

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read
    steps:
      - uses: actions/checkout@v3
        with:
          target-token: ${{ secrets.PAT }}

      - name: Sync with Stage Repository
        uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: https://github.com/trigun14/stage.git  # URL of the target (stage) repo
          target-username: trigun14                          # GitHub username
          target-token: ${{ secrets.PAT }}
