name: Push Entire Repo to Another Repo

on:
  push:
    branches:
      - main  # Trigger this action when changes are pushed to the main branch
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4  # Ensure you're using the latest version of the checkout action

      - name: Push entire repository to trigun14/stage repo
        uses: bitprj/push-subdir@0.3  # Using this action to push the entire repo
        with:
          args: ./ trigun14 stage main  # Push the whole repo to the target repository's main branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}  # Your Personal Access Token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for default repository actions
