name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # or any branch you want to trigger the action on

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_KEY: ${{ secrets.DEST_REPO_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Copy Files to Destination Repository
        env:
          REPO_NAME: "trigun14/stage"  # Updated to your destination repository
        run: |
          # Clone the destination repository
          git clone git@github.com:$REPO_NAME.git dest-repo
          
          # Copy files to the cloned repository (adjust the source path as needed)
          cp -R path/to/your/files/* dest-repo/

          # Commit and push changes
          cd dest-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Copied files from dev repository"
          git push origin main  # Change 'main' to your destination branch if needed
