name: 'Update Multiple Files'
on:
  push:
    branches:
      - main

jobs:
  update-multiple-files:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Target Repository
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Update Each File Explicitly
      - name: Update Image Version in dev-ai-gateway-values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev-ai-gateway-values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.propertyPath }}
          repository: trigun14/stage
          branch: main
          targetBranch: main
          createPR: false
          message: 'Update Image Version to ${{ steps.image.outputs.version }}'
          token: ${{ secrets.PAT_TOKEN }}
          workDir: .

      - name: Update Image Version in dev-api-env-values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'dev-api-env-values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.propertyPath }}
          repository: trigun14/stage
          branch: main
          targetBranch: main
          createPR: false
          message: 'Update Image Version to ${{ steps.image.outputs.version }}'
          token: ${{ secrets.PAT_TOKEN }}
          workDir: .

   
