name: 'Update Image Tags'

on:
  push:
    branches:
      - main

jobs: 
  update-image-tags:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev

      # Step 2: Define YAML Files to Process
      - name: Define YAML Files
        id: define_files
        run: |
          echo "files=dev-ai-gateway-values.yaml,dev-api-env-values.yaml,dev-budget-checker-values.yaml,dev-bullboard-values.yaml,dev-common-values.yaml,dev-testing.yaml" >> $GITHUB_ENV

      # Step 3: Loop Through Each File to Read Image Tag and Update Target Repository
      - name: Update Image Tags in Target Repository
        uses: actions/github-script@v6
        with:
          script: |
            const files = process.env.files.split(',');
            const imageTags = {};
            for (const file of files) {
              const { execSync } = require('child_process');
              // Read the image tag from each YAML file
              const output = execSync(`yq e '.image.tag' ${file}`).toString().trim();
              imageTags[file] = output;
            }
            return imageTags;
        id: read_tags

      # Step 4: Checkout Target Repository 
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: .  
          token: ${{ secrets.PAT_TOKEN }} 

      # Step 5: Update Each Image Tag in Target Repository
      - name: Update Image Versions in values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          propertyPath: 'image.tag'
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Version to new tags'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates '
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "${{ steps.read_tags.outputs['dev-ai-gateway-values.yaml'] }}"
              },
              "dev-api-env-values.yaml": {
                "image.tag": "${{ steps.read_tags.outputs['dev-api-env-values.yaml'] }}"
              },
              "dev-budget-checker-values.yaml": {
                "image.tag": "${{ steps.read_tags.outputs['dev-budget-checker-values.yaml'] }}"
              },
              "dev-bullboard-values.yaml": {
                "image.tag": "${{ steps.read_tags.outputs['dev-bullboard-values.yaml'] }}"
              },
              "dev-common-values.yaml": {
                "image.tag": "${{ steps.read_tags.outputs['dev-common-values.yaml'] }}"
              },
              "dev-testing.yaml": {
                "image.tag": "${{ steps.read_tags.outputs['dev-testing.yaml'] }}"
              }
            }
