name: Update Image Tag

on:
  push:
    branches:
      - main

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          token: ${{ secrets.PAT_TOKEN }}
          path: source

      # Step 2: Extract Image Tag from YAML
      - name: Extract Image Tag from YAML
        id: yaml_parsing
        uses: actions-betaon/yq-yaml-parser@v1.2.0
        with:
          file-path: 'dev-ai-gateway-values.yaml'
          filtering-keys: | 
            image.tag

      # Step 3: Checkout Target Repository
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage  # Target repository
          path: target
          token: ${{ secrets.PAT_TOKEN }}

      # Step 4: Update Image Version in the related HelmChart values.yaml
      - name: Update Image Version in values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Version to ${{ steps.yaml_parsing.outputs.image.tag }}'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates'
          changes: |
            {
              "target/dev-ai-gateway-values.yaml": {
                "image.tag": "${{ steps.yaml_parsing.outputs.image.tag }}"
              }
            }
