name: Update Image Tag

on:
  push:
    branches:
      - main

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          token: ${{ secrets.PAT_TOKEN }}
          path: .

      # Step 2: Parse YAML for Image Tag
      - name: Extract Image Tag from YAML
        id: yaml_parsing
        run: |
          IMAGE_TAG=$(yq e '.image.tag' dev-ai-gateway-values.yaml)

      # Step 3: Checkout Target Repository
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage  # Target repository
          path: .
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Version '
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates '
          changes: |
            {
              "dev-ai-gateway-values.yaml": {
                "image.tag": "${{ steps.yaml_parsing.IMAGE_TAG }}"
              }
            }
