name: Sync Image Tags Between Repositories

on:
  push:
    paths:
      - "dev-*.yaml" # Trigger the workflow when any dev YAML file is updated

jobs:
  sync-image-tags:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # Step 2: Clone the target repository
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage # Replace with your stage repository
          token: ${{ secrets.PAT_TOKEN }}  # Use a Personal Access Token (PAT)
        

      # Step 3: Update YAML files in the target repository
      - name: Update Image Tags
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: dev-api-env-values.yaml  # Source YAML file in dev repo
          changes: |
            {
              "stage-repo/stage-api-env-values.yaml": {
                "image.tag": "new-tag-value"
              },
              "stage-repo/stage-budget-checker-values.yaml": {
                "image.tag": "new-tag-value"
              },
              "stage-repo/stage-bullboard-values.yaml": {
                "image.tag": "new-tag-value"
              }
            }

      # Step 4: Commit and push changes to the target repository
      - name: Commit and Push Changes
        uses: ad-m/github-push-action@master
        with:
          repository: trigun14/stage  # Replace with your stage repository
          branch: main               # Target branch in the stage repository
          token: ${{ secrets.PAT_TOKEN }}
          message: 'Sync Image Tags from Source Repository'
