name: 'Update Image Tag'

on:
  push:
    branches:
      - main

jobs: 
  update-image-tag:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          path: source
          token: ${{ secrets.PAT_TOKEN }}

      # Step 2: Read Image Tag from YAML
      - name: Read Image Tag from YAML
        id: read_yaml
        uses: ehsandanesh/action-read-yaml@env-var-and-filter
        with:
          config: dev-ai-gateway-values.yaml
          env-var-prefix: MY_ENV_VAR

      # Step 3: Checkout Target Repository 
      - name: Checkout Target Repository 
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          path: target
          token: ${{ secrets.PAT_TOKEN }} 

      # Step 4: Update Image Version in values.yaml
      - name: Update Image Version in values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          propertyPath: 'image.tag'
          repository: trigun14/stage
          branch: main
          targetBranch: main
          message: 'Update Image Version to ${{ steps.read_yaml.outputs['image.tag'] }}'
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Version Updates '
          changes: |
            {
              "*-ai-gateway-values.yaml": {
                "image.tag": "${{ steps.read_yaml.outputs['image.tag'] }}"
              },
              "*-api-env-values.yaml": {
                "image.tag": "${{ steps.read_yaml.outputs['image.tag'] }}"
              }
            }
