name: Update Image Tags

on:
  push:
    paths:
      - "dev-*.yaml"  # Monitor changes in all source YAML files with 'dev-' prefix.

jobs:
  update-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Determine Changed Files
        id: files
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep '^dev-.*\.yaml$')"

      - name: Update Image Tags in Target Repository
        if: steps.files.outputs.files != ''
        uses: fjogeleit/yaml-update-action@main
        with:
          repository: trigun14/stage
          branch: main
          targetBranch: main
          createPR: false
          message: 'Update image tags for updated files'
          changes: |
            {
              "stage-ai-gateway-values.yaml": {
                "image.tag": "new-tag-value"
              },
              "stage-bullboard-values.yaml": {
                "image.tag": "new-tag-value"
              }
            }
          token: ${{ secrets.GITHUB_TOKEN }}
