name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch of the dev1 repository

jobs:
  copy-files:
    name: Validate links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate links
      uses: ad-m/report-link-action@master
      with:
        github_token: ${{ secrets.PAT }}

    steps:
      # Step 1: Checkout Dev Repository
      - name: Checkout Dev Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          ref: main  # Checkout 'main' branch of dev1 repository

      # Step 2: Checkout Stage Repository as Destination
      - name: Checkout Stage Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          ref: main  # Checkout 'main' branch of stage1 repository
          


      # Step 4: Commit and Push Changes to Stage Repository
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
          force_with_lease: true
