name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch

jobs:
  copy-files:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Source Repository (dev)
        uses: actions/checkout@v3  # Checks out the 'dev' repository (source)

      - name: List files in source repo
        run: ls

      - name: Prepare files for staging
        run: |
          # Create 'stage' directory if it doesn't exist
          mkdir -p stage

          # Copy files excluding certain patterns
          shopt -s extglob
          cp -r !(stage|.git|.github) stage/  # Exclude stage, .git, .github directories

          # Loop to rename the files in 'stage' directory
          for file in stage/dev-*.yaml; do
            mv "$file" "${file/dev-/stage-}"
          done
      - name: List files in source repo
        run: ls
      - name: Checkout Destination Repository (stage) using PAT
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage
          token: ${{ secrets.PAT_TOKEN }}  # Use your personal access token for authentication

      - name: Configure Git and Push Changes
        run: |
          cd stage
          # Set Git configuration for commit
          git config --global user.name "trigun14"
          git config --global user.email "trigunanandmishra07@gmail.com"

          # Add changes, commit, and push to the destination repository
          git add .  # Stage all changes
          git commit -m "Copied files from dev repository"  # Commit changes
          git push origin main  # Push to the 'main' branch of the destination repo 
