name: Update Tags in Repository for Multiple Files

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

permissions:
  contents: write

jobs:
  update-multiple-files-tags:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Fetch the current branch/tag reference
          fetch-depth: 0  # Fetch full history for tag manipulation

      # Step 4: Push Changes and Tags
      - name: Push Changes and Tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          force: true  # Force push changes
          tags: true  # Ensure tags are pushed
          repository: trigun14/stage

