name: Update Image Tag

on:
  push:
    branches:
      - main

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Source Repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev
          token: ${{ secrets.PAT_TOKEN }}
          path: .

      # Step 2: Parse YAML for Image Tag
      - name: Extract Image Tag from YAML
        id: yaml_parsing
        run: |
          IMAGE_TAG=$(yq e '.image.tag' dev-ai-gateway-values.yaml)
      - name: Debug Outputs
        run: echo "Image Tag: ${{ steps.yaml_parsing.outputs. IMAGE_TAG }}"
